apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .values.Service.type }}
  selector:
    # labels are used as delectors
    project: roboshop
    component: frontend 
  ports:
  - protocol: TCP
    port: 80 #sevice port (internal cluster IP)
    targetPort: 80      