apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations: 
    kubernetes.io/change-cause: {{ .Values.deployment.changeCause }}
spec:
    replicas: {{ .values.deployment.replicas }}
     # using these labels replica set selects the pod
    selector:
      matchLabels:  
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
      # This is pod definition, pod is subset of replicaset
    template:
      metadata:
       labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend 
      spec:
        containers:
        - name: nginx
          image: nginx:{{ .values.deployment.imageVersion }}    
